# Eat Safe, Love

## Notebook Set Up

In [48]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd
#setting max column width
pd.options.display.max_colwidth = 15

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [58]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': {'$eq': 20}}

# Use count_documents to display the number of documents in the result
hygiene_score_20 = establishments.count_documents(query)
print(hygiene_score_20)
print('-----------------------------')
# Display the first document in the results using pprint
hygiene_20_results = list(establishments.find(query))

pprint(hygiene_20_results[0])

41
-----------------------------
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64812cf45813111e5c0606ab'),
 'geocode': {'latitude': Decimal128('50.769705'),
             'longitude': Decimal128('0.27694')},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [53]:
# Convert the result to a Pandas DataFrame
hygiene_20_df = pd.DataFrame(hygiene_20_results)

# Display the number of rows in the DataFrame
print('Rows in DataFrame: ', len(hygiene_20_df))
# Display the first 10 rows of the DataFrame
hygiene_20_df.head(10)

Rows in DataFrame:  41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,64812cf4581...,110681,0,4029,The Chase R...,Caring Prem...,5,5-6 Southfi...,Eastbourne,East Sussex,...,http://www....,Customerfir...,{'Hygiene':...,FHRS,{'longitude...,,4613.888288,False,{'dataSourc...,[{'rel': 's...
1,64812cf4581...,612039,0,1970/FOOD,Brenalwood,Caring Prem...,5,Hall Lane,Walton-on-t...,Essex,...,http://www....,fhsadmin@te...,{'Hygiene':...,FHRS,{'longitude...,,4617.965824,False,{'dataSourc...,[{'rel': 's...
2,64812cf5581...,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed &...,7842,53 Marine P...,Clacton On Sea,Essex,...,http://www....,fhsadmin@te...,{'Hygiene':...,FHRS,{'longitude...,,4619.656144,False,{'dataSourc...,[{'rel': 's...
3,64812cf5581...,172735,0,PI/000023858,Seaford Pizza,Takeaway/sa...,7844,4 High Street,Seaford,East Sussex,...,http://www....,ehealth.ldc...,{'Hygiene':...,FHRS,{'longitude...,,4620.421725,False,{'dataSourc...,[{'rel': 's...
4,64812cf5581...,172953,0,PI/000024532,Golden Palace,Restaurant/...,1,5 South Street,Seaford,East Sussex,...,http://www....,ehealth.ldc...,{'Hygiene':...,FHRS,{'longitude...,,4620.437179,False,{'dataSourc...,[{'rel': 's...
5,64812cf6581...,512854,0,12/00816/BUTH,Ashby's But...,Retailers -...,4613,777 Southch...,Southend-On...,Essex,...,http://www....,Environment...,{'Hygiene':...,FHRS,{'longitude...,,4625.565258,False,{'dataSourc...,[{'rel': 's...
6,64812cf6581...,1537089,0,22/00224/RE...,South Sea E...,Restaurant/...,1,33 Alexandr...,Southend-on...,Essex,...,http://www....,Environment...,{'Hygiene':...,FHRS,{'longitude...,,4626.200132,False,{'dataSourc...,[{'rel': 's...
7,64812cf9581...,155648,0,EH/00006058,Golden Palace,Takeaway/sa...,7844,7 London Road,Rayleigh,Essex,...,http://www....,customerser...,{'Hygiene':...,FHRS,{'longitude...,,4632.276890,False,{'dataSourc...,[{'rel': 's...
8,64812cfa581...,1012883,0,17/00110/MI...,The Tulip Tree,Restaurant/...,1,3 The Village,Chiddingstone,KENT,...,http://www....,environment...,{'Hygiene':...,FHRS,{'longitude...,,4633.934041,False,{'dataSourc...,[{'rel': 's...
9,64812cfb581...,644109,0,41811,F & S,Retailers -...,4613,,81 Southernhay,Basildon,...,http://www....,ehs@basildo...,{'Hygiene':...,FHRS,{'longitude...,,4636.552523,False,{'dataSourc...,[{'rel': 's...

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [55]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {'LocalAuthorityName': {'$regex': "London"}, 'RatingValue': {'$gte': 4}}

# Use count_documents to display the number of documents in the result
rating_over_4 = establishments.count_documents(query)
print(rating_over_4)
print('---------------------')
# Display the first document in the results using pprint
query = {'LocalAuthorityName': {'$regex': "London"}, 'RatingValue': {'$gte': 4}}

london_results = list(establishments.find(query))

pprint(london_results[0])

33
---------------------
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64812cf75813111e5c0620c6'),
 'geocode': {'latitude': Decimal128('51.369321'),
             'longitude': Decimal128('0.508551')},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [56]:
# Convert the result to a Pandas DataFrame
london_df = pd.DataFrame(london_results)

# Display the number of rows in the DataFrame
print('Rows in DataFrame: ', len(london_df))
# Display the first 10 rows of the DataFrame
london_df.head(10)

Rows in DataFrame:  33

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,64812cf7581...,621707,0,PI/000025307,Charlie's,Other cater...,7841,Oak Apple F...,Sheppy Kent,,...,http://www....,publicprote...,{'Hygiene':...,FHRS,{'longitude...,,4627.439468,False,{'dataSourc...,[{'rel': 's...
1,64812cf8581...,1130836,0,PI/000034075,Mv City Cru...,Other cater...,7841,Cherry Gard...,Cherry Gard...,Charlton,...,http://www....,publicprote...,{'Hygiene':...,FHRS,{'longitude...,,4627.873179,False,{'dataSourc...,[{'rel': 's...
2,64812cf9581...,293783,0,PI/000002614,Benfleet Mo...,Other cater...,7841,Ferry Road,South Benfl...,,...,http://www....,publicprote...,{'Hygiene':...,FHRS,{'longitude...,,4631.968418,False,{'dataSourc...,[{'rel': 's...
3,64812cfb581...,1315095,0,PI/000036464,Coombs Cate...,Restaurant/...,1,Leslie Ford...,Tilbury,Charlton,...,http://www....,publicprote...,{'Hygiene':...,FHRS,{'longitude...,,4636.846754,False,{'dataSourc...,[{'rel': 's...
4,64812cfb581...,294474,0,PI/000014647,Tilbury Sea...,Restaurant/...,1,Tenants Row...,Tilbury Essex,,...,http://www....,publicprote...,{'Hygiene':...,FHRS,{'longitude...,,4636.847650,False,{'dataSourc...,[{'rel': 's...
5,64812cfc581...,294900,0,PI/000019066,Mv Valulla,Other cater...,7841,Reeds River...,London,,...,http://www....,publicprote...,{'Hygiene':...,FHRS,{'longitude...,,4640.460834,False,{'dataSourc...,[{'rel': 's...
6,64812d01581...,293756,0,PI/000002538,Tereza Joanne,Other cater...,7841,Funcraft UK...,London,,...,http://www....,publicprote...,{'Hygiene':...,FHRS,{'longitude...,,4648.301822,False,{'dataSourc...,[{'rel': 's...
7,64812d01581...,878523,0,PI/000029844,Brick Lane ...,Restaurant/...,1,Air side Lo...,London,,...,http://www....,publicprote...,{'Hygiene':...,FHRS,{'longitude...,,4649.173485,False,{'dataSourc...,[{'rel': 's...
8,64812d01581...,293772,0,PI/000002585,The Nuance ...,Retailers -...,4613,Duty Free S...,London City...,,...,http://www....,publicprote...,{'Hygiene':...,FHRS,{'longitude...,,4649.188826,False,{'dataSourc...,[{'rel': 's...
9,64812d01581...,294606,0,PI/000016185,WH Smith,Retailers -...,4613,London City...,Silvertown ...,,...,http://www....,publicprote...,{'Hygiene':...,FHRS,{'longitude...,,4649.188850,False,{'dataSourc...,[{'rel': 's...

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [ ]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.49014200
longitude = 0.08384000

query = {'$geocode'}
sort =  

# Print the results

In [ ]:
# Convert result to Pandas DataFrame

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [46]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
hygiene_query = {'$match': {'scores.Hygiene': {'$eq': 0}}}
# 2. Groups the matches by Local Authority
group_query = {'$group': {'_id': '$LocalAuthorityName', 'count': {'$sum': 1}}}
# 3. Sorts the matches from highest to lowest
sort_values = {'$sort': {'count': -1}}

pipeline = [hygiene_query, group_query, sort_values]

results = list(establishments.aggregate(pipeline))
# Print the number of documents in the result
print(len(results))
# Print the first 10 results
pprint(results[0:10])

55
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [50]:
# Convert the result to a Pandas DataFrame
establishments_hygiene_sorted = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print('Rows in DataFrame:', len(establishments_hygiene_sorted))

# Display the first 10 rows of the DataFrame
establishments_hygiene_sorted.head(10)

Rows in DataFrame: 55

              _id  count
0          Thanet   1130
1       Greenwich    882
2       Maidstone    713
3          Newham    711
4           Swale    686
5      Chelmsford    680
6          Medway    672
7          Bexley    607
8  Southend-On...    586
9        Tendring    542